src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 */
class Products
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $featured_image;

    /**
     * @Vich\UploadableField(mapping="products", fileNameProperty="featured_image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isBest;

    /**
     * @ORM\ManyToOne(targetEntity=Fashion::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fashion;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(string $featured_image): self
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getIsBest(): ?bool
    {
        return $this->isBest;
    }

    public function setIsBest(bool $isBest): self
    {
        $this->isBest = $isBest;

        return $this;
    }

    public function getFashion(): ?Fashion
    {
        return $this->fashion;
    }

    public function setFashion(?Fashion $fashion): self
    {
        $this->fashion = $fashion;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Data\Cart;
use App\Entity\Products;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this -> entityManager = $entityManager;
    }

    /**
     * @Route("/mon-panier", name="cart")
     */
    public function index(Cart $cart): Response
    {
        
        return $this->render('cart/index.html.twig',[
            'cart' => $cart ->getFull()
        ]);
    }

     /**
     * @Route("/cart/add/{id}", name="add_cart")
     */
    public function add(Cart $cart, $id)
    {
        $cart->add($id);

        return $this->redirectToRoute('cart');
    }

     /**
     * @Route("/cart/delete/{id}", name="delete_cart")
     */
    public function delete(Cart $cart, $id)
    {
        $cart->delete($id);

        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/decreaser/{id}", name="decreaser_cart")
     */
    public function decreaser(Cart $cart, $id)
    {
        $cart->decreaser($id);

        return $this->redirectToRoute('cart');
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier - La Boutique{% endblock %}

{% block body %}
<h3>Mon Panier</h3>
Retrouvez l'ensemble des produits que vous avez ajouté à votre panier. <br> <br>
{% if (cart|length)>0 %}
<table class="table">
  <thead>
    <tr>
      <th>Produits</th>
      <th>Quantite</th>
      <th>Prix</th>
      <th>Totale</th>
      <th></th>

    </tr>
  </thead>
  <tbody>
    {% set total = null %}
    {% for product in cart %}
    <tr>
        <td>
            <img src="/images/products/{{product.product.featuredImage}}" alt="" height="75px">
            {{ product.product.name }}
        </th>
        <td>
          <a href="{{ path('decreaser_cart', {'id':product.product.id})}}"><img src="{{ asset('assets/img/moins.png')}}" alt="Decresser" height="14px"> </a> 
          {{ product.quantity }}
          <a href="{{ path('add_cart', {'id':product.product.id})}}"><img src="{{ asset('assets/img/plus.png')}}" alt="Ajouter" height="14px"> </a>   
            </td>
        <td>{{ (product.product.price/100) | number_format(2, ',') }}€</td>
        <td>{{ (product.product.price * product.quantity/100) | number_format(2, ',') }}€</td>
        <td>
         <a href="{{ path('delete_cart', {'id':product.product.id})}}"><img src="{{ asset('assets/img/delete.png')}}" alt="Supprimer_mon_panier" height="40px"> </a> 
        </td>
    </tr>
    {% set total = total + (product.product.price * product.quantity) %}
    {% endfor %}
  </tbody>
</table>
<div class="text-right mb-5">
    <b>Nombres de Produits:</b> {{ cart|length}} <br>
    <b>Totale de Mon Panier:</b>  {{ (total /100) | number_format(2, ',') }}€<br> <br> 
    <a href="{{ path('order')}}" class="btn btn-info btn-block"> Valider</a>
</div>
{% else %}
<hr>
<p> <b>Votre panier est vide</b> </p>
{% endif %}

{% endblock %}